services:
  mysql:
    image: bitnami/mysql:latest
    container_name: api_lab
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: apilab
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    ports:
      - "3306:3306"
    volumes:
      - db_data:/bitnami/mysql

volumes:
  db_data:
